---
- hosts: node
  tasks: 
  - name: Restart sshd service
    service:
      name: sshd
      state: restarted
    register: service_status

  - name: Service status
    debug:
      msg: "{{ service_status }}"
