---
- hosts: node1
  tasks:
  - name: Nginx Service Statuss
    command: systemctl status nginx.service
    register: service_status

 - name: Nginx_Service_Status
   debug:
     msg: "{{service_status.stdout_lines}}"
