---
- hosts: node
  tasks: 
  - name: sshd service status
    service:
      name: sshd
      state: restarted
    register: service_status

  - name: Service status
    debug:
      msg: "{{ service_status.status }}"
