---
- hosts: node

  tasks:
    
    - name: Status of nodes
      command: uptime
      register: uptime_status

    - name: Status of disk
      command: df -Th
      register: disk_status

    - name: Uptime of nodes
      debug:
        msg: "Uptime: {{ uptime_status.stdout }}" 

    - name: Disk status
      debug:
        msg: "{{ disk_status.stdout_lines}}"

    - name: LSBLK
      command: lsblk
      register: lsblk_status

    - name: LSBLK_status
      debug:
        msg: "LSBLK: {{ lsblk_status }}" 
