---
- hosts: node

  tasks:
    
    - name: Status of nodeeeeeeeeeeeeeeeeee
      command: uptime
      register: uptime_status

    - name: Status of disk
      command: df -Th
      register: disk_status

    - name: Uptime of nodee
      debug:
        msg: "Uptime: {{ uptime_status.stdout }}" 

    - name: Disk status_new
      debug:
        msg: "{{ disk_status.stdout_lines}}"

    - name: LSBLK_new_status
      command: lsblk
      register: lsblk_status

    - name: LSBLK_statuss_node
      debug:
        msg: "LSBLK: {{ lsblk_status.stdout }}" 
